repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
        args: ["./src/"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241  # Use the latest version
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E501"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the latest version
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        env:
          MYPYPATH: "./"